language: java

sudo: false

script:
  - chmod a+x ./gradlew
  - ./gradlew check

after_success:
  - ./gradlew test jacocoTestReport coveralls

notifications:
  email:
    recipients:
      - smartmapperproject@gmail.com
    on_success: always
    on_failure: always
