language: java

sudo: false

script: "sbt clean coverage test"
  - chmod a+x ./gradlew
  - ./gradlew check

after_success:
  - ./gradlew jacocoRootReport coveralls

notifications:
  email:
    recipients:
      - smartmapperproject@gmail.com
    on_success: always
    on_failure: always
