language: java
branches:
  only:
    - master
    - develop
addons:
  sonarcloud:
    organization: smartmapperproject
    token: $SONAR_TOKEN

sudo: false

script:
 - sbt clean coverage test"
 - chmod a+x ./gradlew
 - ./gradlew check
 - sonar-scanner

after_success:
  - ./gradlew jacocoRootReport coveralls

notifications:
  email:
    recipients:
     - smartmapperproject@gmail.com
    on_success: always
    on_failure: always