language: java

sudo: false

script:
  - chmod a+x ./gradlew
  - ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - smartmapperproject@gmail.com
    on_success: always
    on_failure: always
