@startuml
!include style/commons.style

actor "Utilisateur" as utilisateur
participant ": Map" as map


activate utilisateur
activate map
utilisateur -> map: LeafletMap()
utilisateur -> map: RoutingMachine()

map -> map : calcul itinéraire {rayon}
deactivate map
alt rayon > limite
    utilisateur <-- map : interdit (cerle rouge)
else
    utilisateur <-- map : permis (cerle bleu)
end


deactivate utilisateur


@enduml