@startuml
!include style/commons.style
actor "Utilisateur" as utilisateur
participant ": Front" as frontend
participant ": Back" as backend

activate utilisateur
utilisateur -> frontend: choose(category)

activate frontend
activate backend
frontend -> backend: GET/POI{category}

backend --> frontend: ListPOIByCategory()
deactivate backend
utilisateur<-- frontend: displayCategoryList()
utilisateur<-- frontend: displayListPOIByCategory()
deactivate frontend
deactivate utilisateur

@enduml