@startuml
!include style/commons.style

mainframe Observer POI

participant ": Controller" as Controller #pink
participant ": Service" as Service #pink
participant ": observer" as observer #pink

activate observer #green
observer -> observer : notifyObserver
deactivate observer

activate Controller #green
activate Service #green
Controller -> Service: registerObserver
activate observer #green
Service -> observer: notifyObserver

deactivate Controller
deactivate Service
deactivate observer

@enduml