/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smartmapper;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;


@SpringBootApplication(exclude={DataSourceAutoConfiguration.class})
public class AppMain {
    public String getGreeting() {
        return "Hello dolphin.";
    }

    public static void main(String[] args) {
        SpringApplication.run(AppMain.class, args);
        System.out.println(new AppMain().getGreeting());
    }
}
